// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGMv4VLxj9Rb1IC53gGdrMQ3t7lfDgX64',
    appId: '1:766350336554:web:88b7eb9ec8ba1aa6165953',
    messagingSenderId: '766350336554',
    projectId: 'recetario-bfaec',
    authDomain: 'recetario-bfaec.firebaseapp.com',
    storageBucket: 'recetario-bfaec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZtGzVk9m8xLNSILud3QIrDzGEKT1kCpM',
    appId: '1:766350336554:android:c5039420139cc0f2165953',
    messagingSenderId: '766350336554',
    projectId: 'recetario-bfaec',
    storageBucket: 'recetario-bfaec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUxPD8CqIosAVMYfx2uopURmZ6znpMyO0',
    appId: '1:766350336554:ios:8952da0475906c60165953',
    messagingSenderId: '766350336554',
    projectId: 'recetario-bfaec',
    storageBucket: 'recetario-bfaec.appspot.com',
    iosBundleId: 'com.example.recetas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUxPD8CqIosAVMYfx2uopURmZ6znpMyO0',
    appId: '1:766350336554:ios:8952da0475906c60165953',
    messagingSenderId: '766350336554',
    projectId: 'recetario-bfaec',
    storageBucket: 'recetario-bfaec.appspot.com',
    iosBundleId: 'com.example.recetas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGMv4VLxj9Rb1IC53gGdrMQ3t7lfDgX64',
    appId: '1:766350336554:web:bde12d7631152be0165953',
    messagingSenderId: '766350336554',
    projectId: 'recetario-bfaec',
    authDomain: 'recetario-bfaec.firebaseapp.com',
    storageBucket: 'recetario-bfaec.appspot.com',
  );
}
